

service: Address

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs12.x
  region: ap-south-1
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - "logs:CreateLogGroup"
        - "logs:CreateLogStream"
        - "logs:PutLogEvents"
        - "ec2:CreateNetworkInterface"
        - "ec2:DescribeNetworkInterfaces"
        - "ec2:DeleteNetworkInterface"
        - lambda:InvokeFunction
      Resource:
        - arn:aws:lambda:ap-south-1:*:* # Had to add this too

plugins:
  - serverless-offline


functions:
  createUser:
    handler: controller/usercreate.handler
    events:
      - http:
          path: user-create
          method: post
  loginuser:
    handler: controller/loginuser.handler
    events:
      - http:
          path: user-login
          method: post
  useraddress:
    handler: controller/useraddress.handler
    events:
      - http:
          path: user-address
          method: post
  updateaddress:
    handler: controller/updateaddress.handler
    events:
      - http:
          path: update-address
          method: post
  deletuser:
    handler: controller/deletuser.handler
    events:
      - http:
          path: delete-user
          method: post
  deletaddressuser:
    handler: controller/delet_addressuser.handler
    events:
      - http:
          path: delete_addressuser-user
          method: post       
  getuserdetails:
    handler: controller/getuserdetails.handler
    events:
      - http:
          path: get-user
          method: get
  centercreate:
    handler: controller/createCenter.handler
    events:
      - http:
          path: create-center
          method: post
  AddCenter:
    handler: controller/AddCenter.handler
    events:
      - http:
          path: add-center
          method: post         
  DeletCenter:
    handler: controller/DeletCenter.handler
    events:
      - http:
          path: delete-center
          method: post 
  calculatedistance:
    handler: controller/calculatedistance.handler
    events:
      - http:
          path: calculate-distance
          method: post
  getcenterdetails:
    handler: controller/getcenter.handler
    events:
      - http:
          path: get-center
          method: get                  


